version: "3.7"

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - LC_ALL=C.UTF-8
      - TZ=GMT-5

volumes:
  postgres_data: